feat: 404 page
aHub-Tech/hub-site-front pull request #15
Opened 2021-12-07 15:16 UTC by joaom00

2021-12-07 15:45 UTC, caio-emidio commented on .nuxt/routes.json
> +    "component": "/home/joaom/dev/hub-site-front/pages/index.vue",
Isso esta certo? Tem que apontar para teu diretorio?

2021-12-07 15:55 UTC, joaom00 commented on .nuxt/routes.json
> +    "component": "/home/joaom/dev/hub-site-front/pages/index.vue",
Não sei, o nuxt mudou isso sozinho

2021-12-07 16:08 UTC, joaom00 commented on .nuxt/routes.json
> +    "component": "/home/joaom/dev/hub-site-front/pages/index.vue",
Essa pasta tem que ser adicionada no github mesmo?

2021-12-07 17:12 UTC, caio-emidio commented on .nuxt/routes.json
> +    "component": "/home/joaom/dev/hub-site-front/pages/index.vue",
Acho que tem que ser adicionado apenas o error.

2021-12-07 18:31 UTC, pcbrsites commented on .nuxt/routes.json
> +    "component": "/home/joaom/dev/hub-site-front/pages/index.vue",
Era para ta no .gitignore
veja issue: #12  @caio-emidio @joaom00

2021-12-07 18:52 UTC, pcbrsites commented on layouts/error.vue
> +</template>
Talvez fique legal  ter possibilidade mais, status de erros
```vue
<template>
  <main class="main">
    <template v-if="error.statusCode === 404">
      <div class="content">
        <h1 class="title">OPS, PÁGINA NÃO ENCONTRADA...</h1>
        <img class="image" src="/404.png" />
        <a class="link" href="/">VOLTAR AO INICIO</a>
      </div>
    </template>
    <template v-else>
      <div class="content">
        <h1 class="title">OPS, ERRO {{ error.statusCode }}...</h1>
        <img class="image" :src="`https://http.cat/${error.statusCode}`" />
        <a class="link" href="/">VOLTAR AO INICIO</a>
      </div>
    </template>
  </main>
</template>
```

2021-12-07 19:31 UTC, joaom00 commented on layouts/error.vue
> +</template>
Obrigado pela sugestão @pcbrsites, vou fazer isso

2021-12-07 21:37 UTC, caio-emidio requested changes

2021-12-07 21:37 UTC, caio-emidio commented on layouts/error.vue
> +        <img class="image" :src="`https://http.cat/${error.statusCode}`" />
Acho que eh melhor deixar uma imagem padrao pra todos os erros...
nao faz sentido aparecer esse do http.cat ;)

2021-12-07 22:44 UTC, caio-emidio approved these changes

2021-12-07 23:32 UTC, daviprm commented on .nuxt/routes.json
> +    "component": "/home/joaom/dev/hub-site-front/pages/index.vue",
Eu coloquei ela por "engano" quando subi pra dev. Realmente, tem que estar fora.

2021-12-08 00:06 UTC, daviprm approved these changes

2021-12-08 00:14 UTC, merged