fix instagram icon color
aHub-Tech/hub-site-front pull request #36
Opened 2022-01-14 01:48 UTC by BorrachaFox

# Infos

[Link da Issue](https://github.com/aHub-Tech/hub-site-front/issues/30) 

## O que está sendo entregue?

Correção da cor do ícone de Instagram de uma cor solida para uma cor gradiente de acordo com o pedido na Issue

2022-01-14 13:18 UTC, BorrachaFox commented
## Resultado
![image](https://user-images.githubusercontent.com/69317792/149521439-58b86799-c8a4-40cf-805e-0f58000c2105.png)

2022-01-14 14:20 UTC, caio-emidio approved these changes

2022-01-14 22:28 UTC, vcwild requested changes
Foram commitadas 14k de linhas e removidas 7k de linhas devido aos lock packages, nao acredito que façam sentido para esse PR @caio-emidio

2022-01-15 01:14 UTC, pcbrsites approved these changes

2022-01-15 01:14 UTC, merged